const reporter = require("cucumber-html-reporter");

// Configuration for the HTML report
const options = {
  theme: "bootstrap", // You can change the theme to 'simple', 'compact', etc.
  jsonFile: "reports/load-results.json", // Path to the JSON file generated by Cucumber
  output: "reports/report.html", // Path where you want to save the HTML report
  reportSuiteAsScenarios: true, // Group scenarios by their name
  launchReport: true, // Automatically open the report in the browser
  metadata: {
    browser: {
      name: "Chrome" || "unknown",
      version: "89" || "unknown",
    },
    device: "Local test machine",
    platform: {
      name: "MacOS",
      version: "20.04",
    },
  },
};

// Generate the report
reporter.generate(options);
