// src/generators/project.generator.ts
import fs from "fs";
import path from "path";
import { ProjectConfig } from "../types";
import { SampleFeaturesGenerator } from "./samples/sample-features.generator";
import { SampleStepsGenerator } from "./samples/sample-steps.generator";

export class ProjectGenerator {
  generateProjectStructure(config: ProjectConfig, outputPath: string): void {
    // Create main directories
    this.createDirectory(path.join(outputPath, "features"));
    this.createDirectory(path.join(outputPath, "steps"));
    this.createDirectory(path.join(outputPath, "generated"));
    this.createDirectory(path.join(outputPath, "data"));
    this.createDirectory(path.join(outputPath, "reports"));
    fs.mkdirSync(path.join(outputPath, "data"), { recursive: true });
    // Generate package.json
    this.generatePackageJson(outputPath, config);

    // Generate README
    this.generateReadme(outputPath, config);

    // Generate sample feature files
    const featuresGenerator = new SampleFeaturesGenerator();
    featuresGenerator.generate(outputPath);

    // Generate global types for k6 + browser extensions
    this.generateGlobalTypes(outputPath);

    // Generate sample step definitions
    const stepsGenerator = new SampleStepsGenerator();
    stepsGenerator.generate(outputPath, config);

    // Generate .env.example file
    this.generateEnvExample(outputPath);

    // Generate gitignore
    this.generateGitignore(outputPath);

    // Generate tsconfig if TypeScript
    if (config.language === "ts") {
      this.generateTsConfig(outputPath);
    }
  }

  private createDirectory(dirPath: string): void {
    if (!fs.existsSync(dirPath)) {
      fs.mkdirSync(dirPath, { recursive: true });
    }
  }

  private generateGlobalTypes(outputPath: string): void {
    const content = `// Auto-generated by k6-cucumber-steps
export {};

declare global {
  var savedTokens: Record<string, any>;
  var storedAliases: Record<string, any>;
  var lastResponse: any;
  var exportedTokens: Record<string, any>;
  var baseUrl: string;
  var lastPostData: string;
}
`;
    fs.writeFileSync(path.join(outputPath, "global.types.d.ts"), content);
  }

  private generatePackageJson(outputPath: string, config: ProjectConfig): void {
    const pkgPath = path.join(outputPath, "package.json");
    let pkg: any = {};

    // Load existing package.json if it exists
    if (fs.existsSync(pkgPath)) {
      try {
        pkg = JSON.parse(fs.readFileSync(pkgPath, "utf8"));
        console.log("📦 Detected existing package.json — merging...");
      } catch (e) {
        console.warn("⚠️ Invalid package.json. Creating new one.");
        pkg = {};
      }
    }

    // Ensure scripts object exists
    pkg.scripts = pkg.scripts || {};

    // Add/merge our scripts (do NOT replace entire scripts object)
    const lang = config.language === "ts" ? "ts" : "js";
    const newScripts = {
      test: `k6 run generated/test.generated.${lang}`,
      "test:ui": `K6_BROWSER_ENABLED=true k6 run generated/test.generated.${lang}`,
      "test:ui:headed": `K6_BROWSER_HEADLESS=false K6_BROWSER_ENABLED=true k6 run generated/test.generated.${lang}`,
      "test:api": `K6_BROWSER_ENABLED=false k6 run generated/test.generated.${lang}`,
      generate: `k6-cucumber-steps generate -l ${lang}`,
      "generate:ui": `k6-cucumber-steps generate -l ${lang} --tags browser`,
      "generate:api": `k6-cucumber-steps generate -l ${lang} --exclude-tags browser`,
    };

    // Merge: only add/overwrite our scripts, keep others
    Object.assign(pkg.scripts, newScripts);

    // Ensure dependencies objects exist
    pkg.devDependencies = pkg.devDependencies || {};
    pkg.dependencies = pkg.dependencies || {};

    // Add TypeScript if needed
    if (config.language === "ts" && !pkg.devDependencies["typescript"]) {
      pkg.devDependencies["typescript"] = "^5.0.0";
    }

    // Add dotenv-cli for environment variable support
    pkg.devDependencies["dotenv-cli"] = "^11.0.0";

    // Update @types/k6 to latest stable
    pkg.devDependencies["@types/k6"] = "^1.6.0";

    // Set top-level fields (only if not already set)
    pkg.name = pkg.name || "k6-cucumber-test-project";
    pkg.version = pkg.version || "1.0.0";
    pkg.description =
      pkg.description || "k6 test project with Cucumber integration";
    pkg.main =
      pkg.main || (config.language === "ts" ? "src/test.ts" : "test.js");
    pkg.author = pkg.author || config.author;
    pkg.license = pkg.license || "MIT";

    // Write back
    fs.writeFileSync(pkgPath, JSON.stringify(pkg, null, 2) + "\n");
  }

  private generateReadme(outputPath: string, config: ProjectConfig): void {
    const readmeContent = `# K6 Cucumber Test Project

Generated with k6-cucumber-steps by ${config.author}

## Setup

\`\`\`bash
npm install
\`\`\`

## Environment Variables

1. Copy the example environment file:
\`\`\`bash
cp .env.example .env
\`\`\`

2. Edit \`.env\` and fill in your values:
\`\`\`bash
API_BASE_URL=https://api.example.com
TEST_USER_USERNAME=your_username
TEST_USER_PASSWORD=your_password
\`\`\`

3. Run tests with environment variables:
\`\`\`bash
npx dotenv-cli -- k6 run generated/test.generated.ts
\`\`\`

## Running Tests

### Generate k6 scripts from features:
\`\`\`bash
# Generate all tests
npm run generate

# Generate only UI/browser tests (tagged @browser)
npm run generate:ui

# Generate only API tests (non-browser)
npm run generate:api
\`\`\`

### Run tests:
\`\`\`bash
# Run all tests
npm test

# Run only UI/browser tests
npm run test:ui

# Run only API tests
npm run test:api
\`\`\`

## Project Structure
- \`features/\` - Gherkin feature files
  - \`sample.feature\` - API testing examples
  - \`authSample.feature\` - Authentication workflows
  - \`browserSample.feature\` - Browser automation examples
- \`steps/\` - Step definition implementations
- \`generated/\` - Generated k6 scripts
- \`data/\` - Runtime token storage (auto-generated)
- \`reports/\` - HTML and JSON test reports

## Safe Initialization
This project was initialized with \`k6-cucumber-steps init\`.
Existing project files and dependencies were preserved.
`;

    fs.writeFileSync(path.join(outputPath, "README.md"), readmeContent);
  }

  private generateGitignore(outputPath: string): void {
    const gitignoreContent = `node_modules/

*.html
dist/
build/
reports/
data/*.json
.nyc_output/
coverage/
.env
`;

    fs.writeFileSync(path.join(outputPath, ".gitignore"), gitignoreContent);
  }

  private generateTsConfig(outputPath: string): void {
    const tsconfig = {
      compilerOptions: {
        target: "ES2020",
        module: "commonjs",
        strict: true,
        esModuleInterop: true,
        skipLibCheck: true,
        forceConsistentCasingInFileNames: true,
        types: ["k6"],
        allowImportingTsExtensions: true,
        noEmit: true,
      },
      include: ["src/**/*", "steps/**/*", "**/*.ts", "**/*.d.ts"],
      exclude: ["node_modules"],
    };

    fs.writeFileSync(
      path.join(outputPath, "tsconfig.json"),
      JSON.stringify(tsconfig, null, 2),
    );
  }

  private generateEnvExample(outputPath: string): void {
    const envExampleContent = `# Base URLs
API_BASE_URL=https://jsonplaceholder.typicode.com
AUTH_BASE_URL=https://demoqa.com

# Test User Credentials
TEST_USER_USERNAME=your_test_username
TEST_USER_PASSWORD=your_test_password

# Post Data
POST_TITLE=My Test Post

# OAuth2 Client Credentials (if applicable)
CLIENT_ID=your_client_id
CLIENT_SECRET=your_client_secret
`;

    fs.writeFileSync(path.join(outputPath, ".env.example"), envExampleContent);
  }
}
