name: Node.js Package Workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install k6
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends k6
      - name: Verify k6 Installation
        run: k6 version
      - name: Install Dependencies
        run: npm install
      - name: List Dependencies
        run: npm list --all
      - name: Run Load Tests
        run: npm loadTest
